export { scrollScreen, getscrllInfo } from './largeScreen'
export { getBullyScreen, setBullyScreen } from './bullyscreen'
export { setGifts, getGifts } from './giftset'
export { getMagic, setMagic } from './magicset'
export { getUserList, editUser, userStatus } from './userlist'
